// Generated by usub.cpp.py.

#ifndef usub_cpp
#define usub_cpp

#include <stdio.h>
#include <string.h>

#include "umat_data.h"

#include "UMAT_C_ELASTICITY_1D/umat.cpp"
#include "UMAT_C_ELASTICITY_ISO/umat.cpp"

/**
 *
 * This is the general UMat function.
 * Depending on the name of the material model chosen in ABAQUS, the specific UMat function is executed.
 * Before that, a UMatData structure is created, that contains all data given by ABAQUS, but reinterpreted in C++ types (names are conserved).
 *
 */

extern "C" void umat_(
    double *stress,
    double *statev,
    double *ddsdde,
    double *sse,
    double *spd,
    double *scd,
    double *rpl,
    double *ddsddt,
    double *drplde,
    double *drpldt,
    double *stran,
    double *dstran,
    double *time,
    double *dtime,
    double *temp,
    double *dtemp,
    double *predef,
    double *dpred,
    char   *cmname,
    int    *ndi,
    int    *nshr,
    int    *ntens,
    int    *nstatv,
    double *props,
    int    *nprops,
    double *coords,
    double *drot,
    double *pnewdt,
    double *celent,
    double *dfgrd0,
    double *dfgrd1,
    int    *noel,
    int    *npt,
    int    *layer,
    int    *kspt,
    int    *kstep,
    int    *kinc,
    short   cmname_len)
{
    if (strncmp(cmname, "UMAT_C_ELASTICITY_1D", 20) == 0)
    {
        UMatData<umat_c_elasticity_1d::ndim, umat_c_elasticity_1d::nvec, umat_c_elasticity_1d::npro, umat_c_elasticity_1d::nsta> umat_data(stress, statev, ddsdde, sse, spd, scd, rpl, ddsddt, drplde, drpldt, stran, dstran, time, dtime, temp, dtemp, predef, dpred, cmname,  ndi, nshr, ntens, nstatv, props, nprops, coords, drot, pnewdt, celent, dfgrd0, dfgrd1, noel, npt, layer, kspt, kstep, kinc, cmname_len);

        umat_c_elasticity_1d::umat(umat_data);
    }
    if (strncmp(cmname, "UMAT_C_ELASTICITY_ISO", 21) == 0)
    {
        UMatData<umat_c_elasticity_iso::ndim, umat_c_elasticity_iso::nvec, umat_c_elasticity_iso::npro, umat_c_elasticity_iso::nsta> umat_data(stress, statev, ddsdde, sse, spd, scd, rpl, ddsddt, drplde, drpldt, stran, dstran, time, dtime, temp, dtemp, predef, dpred, cmname,  ndi, nshr, ntens, nstatv, props, nprops, coords, drot, pnewdt, celent, dfgrd0, dfgrd1, noel, npt, layer, kspt, kstep, kinc, cmname_len);

        umat_c_elasticity_iso::umat(umat_data);
    }

} // void umat_

#endif // # ifndef usub_cpp
